exp_params:
  batch_size: 32
  # batch_count: 2 # Comment out to use the full validation sets
  number_visualization_batches: 2
  crop_size: 224
  min_max_normalization: False

trainer_params:
  gpu: -1
